# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-13 23:18

"""
Initial database migration for the `payments` app.

This migration defines two models:
1. Services: Represents a billable or trackable service offered by the platform.
2. Wallet_Movements: Tracks financial movements in a company's wallet, like deposits and redemptions.

This file was auto-generated by Django 1.9.5.

Dependencies:
    - companies.0001_initial: Requires the initial schema of the `companies` app.
    - settings.AUTH_USER_MODEL: Depends on the user model defined in project settings.
"""

from __future__ import absolute_import
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Initial migration for the `payments` app.

    Defines the creation of:
    - Services model
    - Wallet_Movements model
    """

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Name of Service')),
                ('codename', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Codename')),
                ('iva', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='IVA')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Total')),
                ('wallet_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Total')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ('order', 'name'),
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Wallet_Movements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[(b'A', 'Deposit'), (b'R', 'Redeem')], default=None, max_length=1, null=True, verbose_name='Type of Movement')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Amount')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Company', verbose_name='Company')),
                ('service', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.Services', verbose_name='Service')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('-date',),
                'verbose_name': 'Money Movement',
                'verbose_name_plural': 'Money Movements',
            },
        ),
    ]
