# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-05 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20160908_2311'),
        ('companies', '0016_auto_20161105_1039'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('free_users', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('max_users', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='PriceSlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slab_period', models.CharField(blank=True, choices=[(b'M', 'Monthly'), (b'Y', 'Yearly')], default=None, max_length=1, null=True)),
                ('expiry_period', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Amount')),
                ('buffered_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Buffered Amount')),
                ('price_per_user', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Price Per User')),
                ('buffered_price_per_user', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Buffered Price Per User')),
                ('currency', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Currency')),
                ('package', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Package')),
            ],
            options={
                'verbose_name': 'Price Slab',
                'verbose_name_plural': 'Price Slabs',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry', models.DateTimeField(blank=True, default=None, null=True)),
                ('added_users', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('company', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('price_slab', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.PriceSlab')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[(b'A', 'Deposit'), (b'R', 'Redeem')], default=None, max_length=1, null=True, verbose_name='Type of Movement')),
                ('reason', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Amount')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Company', verbose_name='Company')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('-timestamp',),
                'verbose_name': 'Money Movement',
                'verbose_name_plural': 'Money Movements',
            },
        ),
        migrations.RemoveField(
            model_name='wallet_movements',
            name='company',
        ),
        migrations.RemoveField(
            model_name='wallet_movements',
            name='service',
        ),
        migrations.RemoveField(
            model_name='wallet_movements',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ('name',), 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='services',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='services',
            name='order',
        ),
        migrations.RemoveField(
            model_name='services',
            name='total',
        ),
        migrations.RemoveField(
            model_name='services',
            name='wallet_amount',
        ),
        migrations.DeleteModel(
            name='Wallet_Movements',
        ),
        migrations.AddField(
            model_name='package',
            name='services',
            field=models.ManyToManyField(to='payments.Services'),
        ),
        migrations.AlterUniqueTogether(
            name='priceslab',
            unique_together=set([('currency', 'slab_period')]),
        ),
    ]
