# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-10 23:47


from __future__ import absolute_import
from django.db import migrations, models

"""
Migration to add a 'balance' field to the Transactions model.

This migration performs the following operation:
- Adds a new DecimalField 'balance' to the Transactions model, which stores
  the balance amount after each transaction.

Dependencies:
    - payments.0004_auto_20161105_1205
"""

class Migration(migrations.Migration):
    """
    Migration class to add 'balance' field to the Transactions model.
    """
    dependencies = [
        ('payments', '0004_auto_20161105_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Balance'),
        ),
    ]
