# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-11 18:12


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion

"""
Migration to add Discount and Discount_Usage models and related fields.

This migration introduces:
- A new 'Discount' model to represent discount offers, with fields like
  name, label, expiry, type, transaction_type, amount, usage limits,
  enabled status, and timestamp.
- A new 'Discount_Usage' model to track usage counts of discounts by companies.
- Many-to-many relationship between Discount and Company through Discount_Usage.
- A foreign key from Discount to Currency for currency specification.
"""

class Migration(migrations.Migration):
    """
    Migration class for adding Discount and Discount_Usage models with relationships.
    """
    dependencies = [
        ('common', '0004_auto_20160908_2311'),
        ('companies', '0016_auto_20161105_1039'),
        ('payments', '0005_transactions_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'', max_length=200, null=True)),
                ('label', models.CharField(blank=True, default=b'', max_length=50, null=True)),
                ('expiry', models.DateField(blank=True, default=None, null=True)),
                ('type', models.CharField(blank=True, choices=[(b'V', 'Value'), (b'P', 'Redeem')], default=None, max_length=1, null=True, verbose_name='Type of Value')),
                ('transaction_type', models.CharField(blank=True, choices=[(b'A', 'Add'), (b'S', 'Subtract')], default=None, max_length=1, null=True, verbose_name='Type of Movement')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Amount')),
                ('max_usage', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('available_to_signups', models.BooleanField(default=True)),
                ('max_usage_per_company', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('enabled', '-expiry'),
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='Discount_Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('used_count', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Discount')),
            ],
            options={
                'ordering': ('discount', 'timestamp'),
                'verbose_name': 'Discount_Usage',
                'verbose_name_plural': 'Discount Usages',
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='companies',
            field=models.ManyToManyField(through='payments.Discount_Usage', to='companies.Company'),
        ),
        migrations.AddField(
            model_name='discount',
            name='currency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Currency'),
        ),
    ]
