# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-11 18:15

"""
Migration to add a ManyToManyField 'plans' to the Discount model.

This migration introduces a relationship between Discount and PriceSlab
models via the 'plans' field, allowing discounts to be associated with
multiple pricing slabs.

Dependencies:
    - payments.0006_auto_20161111_1812
"""

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration class to add 'plans' ManyToManyField on Discount model.
    """
    dependencies = [
        ('payments', '0006_auto_20161111_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='plans',
            field=models.ManyToManyField(to='payments.PriceSlab'),
        ),
    ]
