# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-11 19:46


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_discount_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='label',
            field=models.CharField(blank=True, default=b'', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(blank=True, choices=[(b'V', 'Value'), (b'P', 'Percent')], default=None, max_length=1, null=True, verbose_name='Type of Value'),
        ),
    ]
