# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-12 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20161111_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(blank=True, choices=[(b'A', 'Added'), (b'R', 'Paid')], default=None, max_length=1, null=True, verbose_name='Type of Movement'),
        ),
    ]
