# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-12 13:52


from __future__ import absolute_import
from django.db import migrations, models

"""
Migration to update the 'type' field choices in the Transactions model.

This migration modifies the 'type' field of the Transactions model to
change the choice labels to 'Added' and 'Paid' instead of previous values.
"""

class Migration(migrations.Migration):
    """
    Migration class to update the 'type' field choices in Transactions model.
    """

    dependencies = [
        ('payments', '0008_auto_20161111_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(blank=True, choices=[(b'A', 'Added'), (b'R', 'Paid')], default=None, max_length=1, null=True, verbose_name='Type of Movement'),
        ),
    ]
