# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-16 10:48


from __future__ import absolute_import
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

"""
Migration to create the ScheduledTransactions model.

This migration introduces the ScheduledTransactions model which tracks
scheduled financial transactions associated with companies, discounts,
price slabs, and users. It records the timestamp of the last update and
the count of users added in the schedule.
"""

class Migration(migrations.Migration):
    """
    Migration class to create ScheduledTransactions model.
    """
    dependencies = [
        ('companies', '0017_auto_20161114_1757'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0009_auto_20161112_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name=b'Timestamp')),
                ('added_users', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Company', verbose_name='Company')),
                ('discount', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Discount')),
                ('price_slab', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.PriceSlab')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('-timestamp',),
                'verbose_name': 'Scheduled Transaction',
                'verbose_name_plural': 'Scheduled Transactions',
            },
        ),
    ]
