# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-17 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_scheduledtransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
    ]
