# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-23 14:47


from __future__ import absolute_import
from django.db import migrations, models

"""
Migration to add 'last_day' and 'last_week' fields to the Subscription model.

This migration adds two BooleanFields, 'last_day' and 'last_week', to the Subscription model.
These fields can be used as flags to indicate whether the subscription is in its last day
or last week respectively. Both fields default to False.
"""

class Migration(migrations.Migration):
    """
    Migration class to add 'last_day' and 'last_week' BooleanFields to the Subscription model.
    """
    dependencies = [
        ('payments', '0012_auto_20161201_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_week',
            field=models.BooleanField(default=False),
        ),
    ]
