# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-23 14:47


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20161201_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_week',
            field=models.BooleanField(default=False),
        ),
    ]
