# Generated by Django 5.2.1 on 2025-06-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_country_continent_alter_country_iso2_code_and_more'),
        ('companies', '0024_alter_ban_company_alter_ban_email_and_more'),
        ('payments', '0013_auto_20161223_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='currency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='label',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('A', 'Add'), ('S', 'Subtract')], default=None, max_length=1, null=True, verbose_name='Type of Movement'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(blank=True, choices=[('V', 'Value'), ('P', 'Percent')], default=None, max_length=1, null=True, verbose_name='Type of Value'),
        ),
        migrations.AlterField(
            model_name='priceslab',
            name='currency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency'),
        ),
        migrations.AlterField(
            model_name='priceslab',
            name='package',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.package'),
        ),
        migrations.AlterField(
            model_name='priceslab',
            name='slab_period',
            field=models.CharField(blank=True, choices=[('M', 'Monthly'), ('Y', 'Yearly')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledtransactions',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.discount'),
        ),
        migrations.AlterField(
            model_name='scheduledtransactions',
            name='price_slab',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.priceslab'),
        ),
        migrations.AlterField(
            model_name='scheduledtransactions',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.servicecategory'),
        ),
        migrations.AlterField(
            model_name='services',
            name='enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='company',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_day',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_week',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price_slab',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.priceslab'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(blank=True, choices=[('A', 'Added'), ('R', 'Paid')], default=None, max_length=1, null=True, verbose_name='Type of Movement'),
        ),
    ]
