# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-30 12:25


from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):
    """
    Enforces a uniqueness constraint on TicketCustomFieldValue for the combination of 'ticket' and 'field'.
    This ensures each ticket can only have one value per custom field.
    """
    dependencies = [
        ('helpdesk', '0012_queue_default_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticketcustomfieldvalue',
            unique_together=set([('ticket', 'field')]),
        ),
    ]
