# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-13 23:19


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('file', models.ImageField(max_length=255, upload_to=b'preuploads/', verbose_name='file')),
            ],
            options={
                'ordering': ('-creation_date',),
                'verbose_name': 'Logo Upload',
                'verbose_name_plural': 'Logos Uploads',
            },
        ),
    ]
