# Generated by Django 5.2.1 on 2025-05-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_logos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.ImageField(max_length=255, upload_to='preuploads/', verbose_name='file'),
        ),
    ]
