# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-05-15 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zinnia', '0004_on_delete_arg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='entry',
            index_together=set([]),
        ),
    ]
