# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-27 11:03


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20161027_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='variables',
            field=models.ManyToManyField(blank=True, null=True, to='activities.NotificationTemplateVariable'),
        ),
    ]
