# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-27 13:17


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='actor_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
