# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-27 23:27


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0031_auto_20161008_2222'),
        ('activities', '0007_auto_20161027_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='variables',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='user',
            new_name='actor',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='template',
        ),
        migrations.AddField(
            model_name='activity',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='postulate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.Postulate'),
        ),
        migrations.AddField(
            model_name='activity',
            name='public_postulate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.Public_Postulate'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='NotificationTemplate',
        ),
        migrations.DeleteModel(
            name='NotificationTemplateVariable',
        ),
    ]
