# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-29 02:24


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0031_auto_20161008_2222'),
        ('activities', '0009_auto_20161028_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['seen', '-last_updated'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='activity',
            name='comments',
            field=models.ManyToManyField(to='vacancies.Comment'),
        ),
    ]
