# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-03 17:13


from __future__ import absolute_import
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0010_auto_20161029_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='target',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_target', to=settings.AUTH_USER_MODEL),
        ),
    ]
