# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-03 18:56


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_auto_20161103_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='subject_action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='target_action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
