# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 11:28


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_auto_20161103_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('subject_action', models.CharField(blank=True, max_length=200, null=True)),
                ('action_url', models.URLField(blank=True, default=None, null=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_updated', 'order'],
                'verbose_name': 'Message Chunk',
                'verbose_name_plural': 'Message Chunks',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='message_chunks',
            field=models.ManyToManyField(to='activities.MessageChunk'),
        ),
    ]
