# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-21 10:21


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_auto_20161119_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_chunks',
            field=models.ManyToManyField(to='activities.MessageChunk'),
        ),
    ]
