# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-21 10:27


from __future__ import absolute_import
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0015_notification_message_chunks'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='spotted_by',
            field=models.ManyToManyField(related_name='Spotters', to=settings.AUTH_USER_MODEL),
        ),
    ]
