# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-21 11:21


from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_activity_spotted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='spotted_by',
            new_name='spotters',
        ),
    ]
