# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-19 15:17


from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_auto_20161121_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='public_postulate',
        ),
    ]
