"""
Initial database migration for the `customField` app.

This migration creates models to support a dynamic, user-defined form system
including form templates, fields, field types, options, and value storage.
"""

# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-02 09:28


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
        Defines the initial schema for the `customField` app. This migration includes
        models for field templates, classifications, types, values, and selectable options.
     """

    initial = True

    dependencies = [
        ('companies', '0017_auto_20161114_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Label')),
                ('is_required', models.BooleanField(default=False, verbose_name='Is Required?')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
            },
        ),
        migrations.CreateModel(
            name='FieldClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Label')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Is Visible?')),
                ('requires_options', models.BooleanField(default=True, verbose_name='Requires Options?')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Field Classification',
                'verbose_name_plural': 'Field Classifications',
            },
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Label')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is Enabled?')),
                ('form_field', models.CharField(choices=[(b'CharField', b'CharField'), (b'ChoiceField', b'ChoiceField'), (b'MultipleChoiceField', b'MultipleChoiceField')], max_length=50, verbose_name='Inbuilt Field')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('classification', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='customField.FieldClassification', verbose_name='Classification')),
            ],
            options={
                'verbose_name': 'Field Type',
                'verbose_name_plural': 'Field Types',
            },
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customField.Field')),
            ],
            options={
                'verbose_name': 'FieldValue',
                'verbose_name_plural': 'FieldValues',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Field Option')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_option', to='customField.Field')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Label')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('belongs_to', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
        ),
        migrations.AddField(
            model_name='field',
            name='field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customField.FieldType', verbose_name='Field Type'),
        ),
        migrations.AddField(
            model_name='field',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customField.Template'),
        ),
    ]
