"""
Migration for adding the `field_widget` field to the `FieldType` model and altering the `form_field` field.

This update supports the explicit association of widgets with each field type to enable
more precise form rendering and customization in dynamic forms.
"""

# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-03 15:45


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adds a new field `field_widget` to the `FieldType` model and modifies the `form_field`
    field to include a default value.

    These changes expand the dynamic form system by allowing each field type to specify both
    a form field and a form widget, enabling more customized rendering of forms.
    """

    dependencies = [
        ('customField', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtype',
            name='field_widget',
            field=models.CharField(choices=[(b'TextInput', b'TextInput'), (b'TextArea', b'TextArea'), (b'CheckboxInput', b'CheckboxInput'), (b'Select', b'Select'), (b'SelectMultiple', b'SelectMultiple'), (b'RadioSelect', b'RadioSelect'), (b'CheckboxSelectMultiple', b'CheckboxSelectMultiple')], default=None, max_length=50, verbose_name='Inbuilt Widget'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='form_field',
            field=models.CharField(choices=[(b'CharField', b'CharField'), (b'ChoiceField', b'ChoiceField'), (b'MultipleChoiceField', b'MultipleChoiceField')], default=None, max_length=50, verbose_name='Inbuilt Field'),
        ),
    ]
