# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-22 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customField', '0002_auto_20170403_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtype',
            name='field_widget',
            field=models.CharField(choices=[(b'TextInput', b'TextInput'), (b'Textarea', b'Textarea'), (b'CheckboxInput', b'CheckboxInput'), (b'Select', b'Select'), (b'SelectMultiple', b'SelectMultiple'), (b'RadioSelect', b'RadioSelect'), (b'CheckboxSelectMultiple', b'CheckboxSelectMultiple')], default=None, max_length=50, verbose_name='Inbuilt Widget'),
        ),
    ]
