"""
Migration for fixing the casing of the `Textarea` widget label in the `field_widget` choices
of the `FieldType` model.

This corrects the earlier typo where `TextArea` was capitalized incorrectly. Django expects
widget names like `Textarea`, so this aligns the configuration with Django standards.
"""

# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-22 15:23


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Alters the `field_widget` field in the `FieldType` model to correct the casing of the
    `Textarea` choice.

    This is a maintenance migration to align with Django's correct widget naming conventions.
    """

    dependencies = [
        ('customField', '0002_auto_20170403_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtype',
            name='field_widget',
            field=models.CharField(choices=[(b'TextInput', b'TextInput'), (b'Textarea', b'Textarea'), (b'CheckboxInput', b'CheckboxInput'), (b'Select', b'Select'), (b'SelectMultiple', b'SelectMultiple'), (b'RadioSelect', b'RadioSelect'), (b'CheckboxSelectMultiple', b'CheckboxSelectMultiple')], default=None, max_length=50, verbose_name='Inbuilt Widget'),
        ),
    ]
