# Generated by Django 5.2.1 on 2025-06-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_alter_ban_company_alter_ban_email_and_more'),
        ('customField', '0003_auto_20170822_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='is_required',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Required?'),
        ),
        migrations.AlterField(
            model_name='fieldclassification',
            name='is_visible',
            field=models.BooleanField(blank=True, default=True, verbose_name='Is Visible?'),
        ),
        migrations.AlterField(
            model_name='fieldclassification',
            name='requires_options',
            field=models.BooleanField(blank=True, default=True, verbose_name='Requires Options?'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='classification',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customField.fieldclassification', verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='field_widget',
            field=models.CharField(choices=[('TextInput', 'TextInput'), ('Textarea', 'Textarea'), ('CheckboxInput', 'CheckboxInput'), ('Select', 'Select'), ('SelectMultiple', 'SelectMultiple'), ('RadioSelect', 'RadioSelect'), ('CheckboxSelectMultiple', 'CheckboxSelectMultiple')], default=None, max_length=50, verbose_name='Inbuilt Widget'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='form_field',
            field=models.CharField(choices=[('CharField', 'CharField'), ('ChoiceField', 'ChoiceField'), ('MultipleChoiceField', 'MultipleChoiceField')], default=None, max_length=50, verbose_name='Inbuilt Field'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='is_enabled',
            field=models.BooleanField(blank=True, default=True, verbose_name='Is Enabled?'),
        ),
        migrations.AlterField(
            model_name='template',
            name='belongs_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
    ]
