# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 10:47


from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0012_auto_20160902_1047'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='industry',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
    ]
