# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 23:11


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20160908_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name=b'Code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='decimal_digits',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name=b'No of Decimal Digits'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name=b'Name'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name_plural',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name=b'Plural Name'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='rounding',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name=b'Rounding'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name=b'Symbol'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol_native',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name=b'Native Symbol'),
        ),
    ]
