# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-30 15:29


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20160908_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='cname',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Cname'),
        ),
    ]
