# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-26 19:53


from __future__ import absolute_import
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20161230_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.TextField()),
                ('oauth_secret', models.TextField()),
                ('identifier', models.TextField()),
                ('social_code', models.CharField(choices=[(b'FB', b'Facebook'), (b'TW', b'Twitter'), (b'LI', b'Linked In')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Authentication',
                'verbose_name_plural': 'Social Authentications',
            },
        ),
    ]
