# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-14 15:26


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_socialauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialauth',
            name='photo',
            field=models.ImageField(blank=True, default=b'logos_TRM/logo_TRM_user_default.png', max_length=200, null=True, upload_to=b'photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='socialauth',
            name='social_name',
            field=models.CharField(blank=True, default=b'', max_length=100, null=True),
        ),
    ]
