# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-14 18:36


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20170314_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialauth',
            name='remote_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
