# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-05-15 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_socialauth_remote_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialauth',
            name='photo',
            field=models.ImageField(blank=True, default=b'/static/images/default_user.jpg', max_length=200, null=True, upload_to=b'photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default=b'/static/images/default_user.jpg', max_length=200, null=True, upload_to=b'photos/', verbose_name='Photo'),
        ),
    ]
