# Generated by Django 5.2.1 on 2025-06-12 14:12

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_socialauth_remote_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(blank=True, choices=[('AF', 'Africa'), ('NA', 'North America'), ('EU', 'Europe'), ('AS', 'Asia'), ('OC', 'Oceania'), ('SA', 'South America'), ('AN', 'Antarctica')], default=None, max_length=2, null=True, verbose_name='Continents'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso2_code',
            field=models.CharField(blank=True, default=None, max_length=2, null=True, unique=True, verbose_name='ISO alpha-2'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='decimal_digits',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='No of Decimal Digits'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name_plural',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Plural Name'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='rounding',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Rounding'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Symbol'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol_native',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Native Symbol'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='municipal',
            name='state',
            field=models.ForeignKey(blank=True, limit_choices_to={'pk__exact': 0}, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='socialauth',
            name='photo',
            field=models.ImageField(blank=True, default='logos_TRM/logo_TRM_user_default.png', max_length=200, null=True, upload_to='photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='socialauth',
            name='social_code',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('LI', 'Linked In')], max_length=50),
        ),
        migrations.AlterField(
            model_name='socialauth',
            name='social_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(blank=True, limit_choices_to={'pk__exact': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='logued_by',
            field=models.CharField(blank=True, choices=[('EL', 'Site'), ('FB', 'Facebook'), ('GO', 'Google'), ('LI', 'LinkedIn'), ('TW', 'Twitter')], default=None, max_length=2, null=True, verbose_name='Loggin Method'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='logos_TRM/logo_TRM_user_default.png', max_length=200, null=True, upload_to='photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
