

"""
This module defines the initial database migration for the `candidates` app 
in a Django project. It sets up the foundational database schema required to 
store and manage candidate-related data, such as personal information, academic 
qualifications, professional experiences, certifications, languages, projects, 
and related classifications. This migration includes table creation, model 
relationships, and metadata configurations necessary for the app's core 
functionality.
"""

# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-13 23:18


from __future__ import absolute_import
import candidates.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import re


class Migration(migrations.Migration):
    """
    Defines the initial database schema migration for the 'candidates' app.

    This migration creates multiple models related to candidate information, 
    including education, work experience, skills, languages, and associated entities.

    Attributes:
        initial (bool): Indicates this is the initial migration for the app.
        dependencies (list): Lists other migrations and models this migration depends on.
        operations (list): Defines the database operations to apply in this migration.
    """

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Course Name')),
                ('school', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Institution')),
                ('state', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='State')),
                ('city', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='City')),
                ('start_date', models.DateField(blank=True, default=None, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=None, null=True, verbose_name='End Date')),
            ],
            options={
                'ordering': ['-end_date', '-start_date'],
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='Academic_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Area')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=100, null=True)),
            ],
            options={
                'ordering': ['order', 'name'],
                'verbose_name': 'Academice Area',
                'verbose_name_plural': 'Academice Areas',
            },
        ),
        migrations.CreateModel(
            name='Academic_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Status')),
                ('codename', models.CharField(blank=True, default=None, max_length=15, null=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Status/Academic Status',
                'verbose_name_plural': 'Status/Academic Status',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Surname')),
                ('birthday', models.DateField(blank=True, default=None, null=True, verbose_name='Birthday')),
                ('state', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='State')),
                ('city', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='City')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, null=True)),
                ('cellphone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, null=True)),
                ('travel', models.BooleanField(default=False, verbose_name='Availability to Travel')),
                ('residence', models.BooleanField(default=False, verbose_name='Availability to change residence')),
                ('min_salary', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Minimum Salary')),
                ('max_salary', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Desired Salary')),
                ('linkedin', models.URLField(blank=True, default=None, null=True, verbose_name='Linkedin')),
                ('facebook', models.URLField(blank=True, default=None, null=True, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(re.compile(b'^[\\w.@+-]+$'))], verbose_name='Twitter')),
                ('google', models.URLField(blank=True, default=None, null=True, verbose_name='Google +')),
                ('objective', models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Profesional Objetive')),
                ('skills', models.TextField(blank=True, default=None, max_length=700, null=True, verbose_name='Skills')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Add Date')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('gender', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Gender', verbose_name='Gender')),
                ('maritalStatus', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Marital_Status', verbose_name='Marital Status')),
                ('nationality', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.Country', verbose_name='Nationality')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField()),
                ('candidate', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate', verbose_name='Candidate')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_info', models.BooleanField(default=False, verbose_name='Personal Information?')),
                ('objective', models.BooleanField(default=False, verbose_name='Professional Objective?')),
                ('expertise', models.BooleanField(default=False, verbose_name='Profesional Experience?')),
                ('academic', models.BooleanField(default=False, verbose_name='Academic Information?')),
                ('language', models.BooleanField(default=False, verbose_name='Languages?')),
                ('training', models.BooleanField(default=False, verbose_name='Trainings?')),
                ('certificate', models.BooleanField(default=False, verbose_name='Certificates?')),
                ('project', models.BooleanField(default=False, verbose_name='Projects?')),
                ('file', models.FileField(blank=True, null=True, upload_to=candidates.models.upload_cv_file_path)),
                ('advance', models.IntegerField(blank=True, default=0, null=True, verbose_name='Percent Complete')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Add Date')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('candidate', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate', verbose_name='Candidate')),
            ],
            options={
                'ordering': ['-advance'],
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curricula',
            },
        ),
        migrations.CreateModel(
            name='CV_Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate', verbose_name='Candidate')),
            ],
            options={
                'ordering': ['language'],
                'verbose_name': 'CV Language',
                'verbose_name_plural': 'CV Languages',
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Company')),
                ('state', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='State')),
                ('city', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='City')),
                ('employment', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Post')),
                ('start_date', models.DateField(blank=True, default=None, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=None, null=True, verbose_name='End Date')),
                ('present', models.BooleanField(default=False, verbose_name='Present?')),
                ('tasks', models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='Tasks or Functions')),
                ('candidate', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate', verbose_name='Candidate')),
                ('country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Country', verbose_name='Country')),
                ('industry', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Company_Industry', verbose_name=b'Industry')),
            ],
            options={
                'ordering': ['-present', '-end_date', '-start_date'],
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=True, max_length=20, null=True, verbose_name='Language')),
                ('codename', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=100, null=True)),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Language_Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=True, max_length=15, null=True, verbose_name='Level')),
                ('codename', models.CharField(blank=True, default=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Language Proficiency',
                'verbose_name_plural': 'Language Proficiency',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField()),
                ('candidate', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate', verbose_name='Candidate')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField()),
                ('candidate', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate', verbose_name='Candidate')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
            },
        ),
        migrations.AddField(
            model_name='cv_language',
            name='language',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.Language', verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='cv_language',
            name='level',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.Language_Level', verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='academic',
            name='area',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='candidates.Academic_Area', verbose_name='Academic Area'),
        ),
        migrations.AddField(
            model_name='academic',
            name='candidate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate', verbose_name='Candidate'),
        ),
        migrations.AddField(
            model_name='academic',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='academic',
            name='degree',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Degree', verbose_name='Level of Study'),
        ),
        migrations.AddField(
            model_name='academic',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.Academic_Status', verbose_name='Status'),
        ),
    ]
