
"""This module contains a Django database migration for the 'candidates' application,
generated with Django 1.9.5.

The migration performs schema updates to existing models by:
- Adding a new optional 'public_email' field (EmailField) to the Candidate model,
  allowing candidates to specify a public-facing email address.
- Altering the 'area' field in the Academic model to support null and blank values,
  set a default of None, and provide a more descriptive verbose name 'Specialisation'.

This migration depends on the initial migration '0001_initial' to ensure proper sequencing
and consistency of database schema changes."""

# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 12:47


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration class for applying schema changes to the 'candidates' app models.

    Attributes:
        dependencies (list): Specifies the migration(s) that must be applied before this one.
        operations (list): Contains database schema modification operations to be performed,
                           including adding and altering fields.

    This class inherits from Django's migrations.Migration and encapsulates
    all the database schema transformations for this migration step.
    """

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='public_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='area',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Specialisation'),
        ),
    ]
