# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 20:27


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration class that applies schema modifications to the 'cv_language' model
    within the 'candidates' app.

    Attributes:
        dependencies (list): Migrations that must be applied before this one.
        operations (list): A list of schema-altering operations including:
            - Altering model options for ordering and verbose names.
            - Removing the 'level' field.
            - Adding 'read', 'speak', and 'write' Boolean fields with default False values.

    Inherits from Django's migrations.Migration class.
    """

    dependencies = [
        ('candidates', '0002_auto_20160824_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv_language',
            options={'ordering': ['language'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.RemoveField(
            model_name='cv_language',
            name='level',
        ),
        migrations.AddField(
            model_name='cv_language',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Can Read?'),
        ),
        migrations.AddField(
            model_name='cv_language',
            name='speak',
            field=models.BooleanField(default=False, verbose_name='Can Speak?'),
        ),
        migrations.AddField(
            model_name='cv_language',
            name='write',
            field=models.BooleanField(default=False, verbose_name='Can Write?'),
        ),
    ]
