# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20160824_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv_language',
            options={'ordering': ['language'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.RemoveField(
            model_name='cv_language',
            name='level',
        ),
        migrations.AddField(
            model_name='cv_language',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Can Read?'),
        ),
        migrations.AddField(
            model_name='cv_language',
            name='speak',
            field=models.BooleanField(default=False, verbose_name='Can Speak?'),
        ),
        migrations.AddField(
            model_name='cv_language',
            name='write',
            field=models.BooleanField(default=False, verbose_name='Can Write?'),
        ),
    ]
