# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_public_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='interests',
            field=models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Interests'),
        ),
    ]
