# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 16:13


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration class that handles the addition of the 'interests' field to the
    'Candidate' model in the 'candidates' app.

    Attributes:
        dependencies (list): A list containing the previous migration to preserve order.
        operations (list): A list of operations defining the schema change. In this case,
                           it adds a `TextField` named 'interests' with a max length of 300,
                           and marked as optional.

    Inherits:
        django.db.migrations.Migration
    """

    dependencies = [
        ('candidates', '0004_candidate_public_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='interests',
            field=models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Interests'),
        ),
    ]
