# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_candidate_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='extra_curriculars',
            field=models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Extra Curriculars'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hobbies',
            field=models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Hobbies'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='others',
            field=models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Others'),
        ),
    ]
