# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 16:19


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration class that adds additional descriptive fields to the `Candidate` model
    in the 'candidates' app.

    New Fields Added:
        - extra_curriculars (TextField): Optional, max_length=300, stores extracurricular activities.
        - hobbies (TextField): Optional, max_length=300, stores hobbies.
        - others (TextField): Optional, max_length=300, stores other additional information.

    Attributes:
        dependencies (list): Specifies that this migration depends on '0005_candidate_interests'.
        operations (list): Contains operations to add the three new fields to the database schema.

    Inherits:
        django.db.migrations.Migration
    """

    dependencies = [
        ('candidates', '0005_candidate_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='extra_curriculars',
            field=models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Extra Curriculars'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hobbies',
            field=models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Hobbies'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='others',
            field=models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Others'),
        ),
    ]
