# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 17:05


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration class to update several `TextField` fields in the `Candidate` model.

    Purpose:
        - Standardizes the declaration of optional fields in the Candidate model by
          explicitly setting `null=True`, `blank=True`, and `default=None`.
        - Removes any `max_length` constraint that was previously applied to `TextField` types.
    """

    dependencies = [
        ('candidates', '0006_auto_20160908_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='extra_curriculars',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Extra Curriculars'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hobbies',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Hobbies'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='interests',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Interests'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='others',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Others'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Skills'),
        ),
    ]
