# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 17:53


from __future__ import absolute_import
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_auto_20160908_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='extra_curriculars',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='Extra Curriculars'),
        ),
    ]
