# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 19:55


from __future__ import absolute_import
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    """
    Migration class to modify the `hobbies`, `interests`, and `others` fields in the `Candidate` model.

    Purpose:
        - Converts standard `TextField` instances to `RichTextField` for enhanced user input.
        - Enables better formatting for personal information stored in these fields.

    Attributes:
        dependencies (list): Ensures this migration is applied after '0008_auto_20160908_1753'.
        operations (list): Contains `AlterField` operations for `hobbies`, `interests`, and `others`.

    Inherits:
        django.db.migrations.Migration
    """

    dependencies = [
        ('candidates', '0008_auto_20160908_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='hobbies',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='Hobbies'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='interests',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='Interests'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='others',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='Others'),
        ),
    ]
