# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-27 19:28


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration class to add a `filecontent` field to the `Curriculum` model.

    Purpose:
        - Enables storing the textual content of curriculum documents (CVs) as plain text.
        - Facilitates full-text search, parsing, or preview functionalities within the application.
    """
    dependencies = [
        ('candidates', '0009_auto_20160908_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='filecontent',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
    ]
