# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-03 18:37


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Migration class that introduces additional fields and modifies existing fields in the `Candidate` model."""
    dependencies = [
        ('candidates', '0010_curriculum_filecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='parent_profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicted_profiles', to='candidates.Candidate'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile_source',
            field=models.CharField(blank=True, choices=[(b'SA', b'Site'), (b'PU', b'Public'), (b'FB', b'Facebook'), (b'GO', b'Google'), (b'LI', b'LinkedIn'), (b'TW', b'Twitter')], default=None, max_length=2, null=True, verbose_name='Profile Source'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(blank=True, default=b'', max_length=30, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(blank=True, default=b'', max_length=30, null=True, verbose_name='Surname'),
        ),
    ]
