# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-22 15:23


from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):
    """Migration class to update model options for `Academic` and `Expertise`."""

    dependencies = [
        ('candidates', '0011_auto_20170703_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academic',
            options={'ordering': ['-end_date', '-start_date', 'course_name'], 'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
        migrations.AlterModelOptions(
            name='expertise',
            options={'ordering': ['-present', '-end_date', '-start_date', 'employment'], 'verbose_name': 'Work Experience', 'verbose_name_plural': 'Work Experiences'},
        ),
    ]
