# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-08 16:35


from __future__ import absolute_import
import candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration class that adds the `pdf_file` field to the `Curriculum` model."""

    dependencies = [
        ('candidates', '0012_auto_20170822_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=candidates.models.upload_cv_file_path),
        ),
    ]
