# Generated by Django 5.2.1 on 2025-06-12 14:12

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_curriculum_pdf_file'),
        ('companies', '0024_alter_ban_company_alter_ban_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='candidate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidate', verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='profile_source',
            field=models.CharField(blank=True, choices=[('SA', 'Site'), ('PU', 'Public'), ('FB', 'Facebook'), ('GO', 'Google'), ('LI', 'LinkedIn'), ('TW', 'Twitter')], default=None, max_length=2, null=True, verbose_name='Profile Source'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='public_photo',
            field=models.ImageField(blank=True, default=None, max_length=200, null=True, upload_to='photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='twitter',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'))], verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='candidate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidate', verbose_name='candidate'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='candidate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidate', verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='filecontent',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='cv_language',
            name='candidate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidate', verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='candidate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidate', verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='industry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company_industry', verbose_name='Industry'),
        ),
    ]
