# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-13 23:18


from __future__ import absolute_import
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import re

"""
This Django migration creates initial models for the companies app. These models
include Company, Company_Industry, Recommendation_Status, Recommendations,
Recruiter, and Wallet.

Each model defines fields relevant to company profiles, relationships,
recruiter assignments, financial transactions (wallets), and inter-company recommendations.

Dependencies:
- AUTH_USER_MODEL: Custom user model.
- common.Address and common.Subdomain: Shared address and subdomain data.

Generated by Django 1.9.5.
"""

class Migration(migrations.Migration):
    """
    Represents a registered company with general business information.
    """
    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Tradename')),
                ('social_name', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Busness Name')),
                ('description', models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Short Description')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, null=True, verbose_name='Phone')),
                ('url', models.URLField(blank=True, default=None, null=True, verbose_name='Website')),
                ('facebook', models.URLField(blank=True, default=None, null=True, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, default=None, max_length=16, null=True, validators=[django.core.validators.RegexValidator(re.compile(b'^[\\w.@+-]+$'))], verbose_name='Twitter')),
                ('company_email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='E-mail')),
                ('logo', models.ImageField(blank=True, default=b'logos_TRM/logo_TRM_company_default.jpg', max_length=200, null=True, upload_to=b'companies/logos/')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Add Date')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('address', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Address', verbose_name='Address')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Company_Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Name')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Company Industry',
                'verbose_name_plural': 'Company Industries',
            },
        ),
        migrations.CreateModel(
            name='Recommendation_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Status')),
                ('codename', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Codename')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Order')),
            ],
            options={
                'ordering': ('-order',),
                'verbose_name': 'Status of Recommendation',
                'verbose_name_plural': 'Status of Recommendations',
            },
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=None, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=None, null=True, verbose_name='End Date')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Add Date')),
                ('from_company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='companies.Company', verbose_name='From')),
                ('status', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Recommendation_Status', verbose_name=b'Status')),
                ('to_company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='companies.Company', verbose_name='For')),
            ],
            options={
                'ordering': ('status', 'end_date', 'add_date'),
                'verbose_name': 'Recomendation',
                'verbose_name_plural': 'Recomendations',
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ManyToManyField(default=None, to='companies.Company', verbose_name='Company')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'user')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adds', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Deposit')),
                ('redeems', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Redeem')),
                ('available', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Available')),
                ('company', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company', verbose_name=b'Company')),
            ],
            options={
                'ordering': ['-available'],
                'verbose_name': 'Electronic Wallet',
                'verbose_name_plural': 'Electronic Wallets',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Company_Industry', verbose_name=b'Industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='subdomain',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Subdomain', verbose_name='Subdomain'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name=b'User'),
        ),
    ]
