# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-14 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='company',
            name='nationality',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.Country', verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='State'),
        ),
    ]
