# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-14 13:55


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Migration to update the 'Company' model by removing the 'address' field
    and adding new location-related fields: 'city', 'state', and 'nationality'.

    Changes applied in this migration:
    - Removes the OneToOneField 'address' from 'Company'.
    - Adds a new CharField 'city' to store the company's city.
    - Adds a new CharField 'state' to store the company's state.
    - Adds a ForeignKey 'nationality' linking to the 'Country' model,
      representing the company's nationality.

    Dependencies:
        - Initial migration of 'common' app (0001_initial)
        - Initial migration of 'companies' app (0001_initial)
    """

    dependencies = [
        ('common', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='company',
            name='nationality',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.Country', verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='State'),
        ),
    ]
