# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 11:01


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Migration to create the 'Stage' model in the 'companies' app.

    The 'Stage' model represents different stages associated with a company.

    Fields created:
    - id: Auto-incrementing primary key.
    - name: Optional CharField for the name of the stage (max length 50).
    - company: Optional ForeignKey linking the stage to a 'Company' instance, 
      with SET_NULL on deletion.

    Model options:
    - ordering by 'name'
    - verbose_name set to 'Stages'

    Dependencies:
        - 'companies' migration '0002_auto_20160814_1355'
    """
    dependencies = [
        ('companies', '0002_auto_20160814_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Stage Name')),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Company', verbose_name='Company')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Stages',
            },
        ),
    ]
