# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='No of Employees'),
        ),
    ]
