# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 13:02


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to add the 'no_of_employees' field to the 'Company' model.

    The new field represents the number of employees in a company.

    Field details:
    - no_of_employees: IntegerField, optional (nullable), with a verbose name
      'No of Employees'.

    Dependencies:
        - Applies after the '0003_stage' migration in the 'companies' app.
    """
    dependencies = [
        ('companies', '0003_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='no_of_employees',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='No of Employees'),
        ),
    ]
