# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-16 11:36


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to alter the 'logo' field of the 'Company' model.

    Changes the default logo image file from 
    'logos_TRM/logo_TRM_company_default.jpg' to 
    'logos_TRM/logo_TRM_company_default.png'.

    Field attributes:
        - blank=True
        - null=True
        - max_length=200
        - upload_to='companies/logos/'

    Dependencies:
        - Depends on migration '0005_auto_20160908_2305' in the 'companies' app.
    """
    dependencies = [
        ('companies', '0005_auto_20160908_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default=b'logos_TRM/logo_TRM_company_default.png', max_length=200, null=True, upload_to=b'companies/logos/'),
        ),
    ]
