# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_recruiterinvitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterinvitation',
            old_name='invitation_token',
            new_name='token',
        ),
    ]
