# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 12:29


from __future__ import absolute_import
from django.db import migrations

"""
Migration to rename the field 'invitation_token' to 'token' in the RecruiterInvitation model.

This migration updates the RecruiterInvitation model by renaming the
'invitation_token' field to 'token' to simplify the field name and improve clarity.

Dependencies:
    - Depends on the '0007_recruiterinvitation' migration in the 'companies' app.
"""

class Migration(migrations.Migration):
    """Migration class to rename a field in RecruiterInvitation model."""
    dependencies = [
        ('companies', '0007_recruiterinvitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterinvitation',
            old_name='invitation_token',
            new_name='token',
        ),
    ]
