# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 12:29


from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):
    """
    Migration to rename a field in the RecruiterInvitation model.

    This migration renames the field 'invitation_token' to 'token' 
    in the 'recruiterinvitation' model to simplify the field name.

    Dependencies:
        - Applies after the migration '0007_recruiterinvitation' in the 'companies' app.
    """
    dependencies = [
        ('companies', '0007_recruiterinvitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterinvitation',
            old_name='invitation_token',
            new_name='token',
        ),
    ]
