# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 13:48


from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):
    """
    Migration to update model options for the Recruiter model.

    This migration sets custom permissions for the Recruiter model, 
    including team management, site management, job management, 
    and application process management. It also defines the verbose 
    names for the model.

    Dependencies:
        - Depends on migration '0008_auto_20160920_1229' in the 'companies' app.
    """
    dependencies = [
        ('companies', '0008_auto_20160920_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruiter',
            options={'permissions': (('team_management', 'Team Management'), ('site_management', 'Site Management'), ('job_management', 'Job Management'), ('application_process_management', 'Application Process Management')), 'verbose_name': 'Recruiter', 'verbose_name_plural': 'Recruiters'},
        ),
    ]
