# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 13:48


from __future__ import absolute_import
from django.db import migrations

"""
Migration to update the Recruiter model's meta options.

This migration adds custom permissions for the Recruiter model to manage 
team, site, jobs, and application processes. It also ensures the verbose 
names for singular and plural forms are set.

Dependencies:
    - Depends on migration '0008_auto_20160920_1229' in the 'companies' app.
"""

class Migration(migrations.Migration):
    """Migration class to alter Recruiter model options."""
    dependencies = [
        ('companies', '0008_auto_20160920_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruiter',
            options={'permissions': (('team_management', 'Team Management'), ('site_management', 'Site Management'), ('job_management', 'Job Management'), ('application_process_management', 'Application Process Management')), 'verbose_name': 'Recruiter', 'verbose_name_plural': 'Recruiters'},
        ),
    ]
