# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 14:01


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to update the Recruiter model's options and add new Boolean fields.

    This migration performs the following operations:
    - Sets the verbose_name and verbose_name_plural options for the Recruiter model.
    - Adds four Boolean fields to the Recruiter model to represent different management permissions:
        * team_management
        * site_management
        * job_management
        * application_process_management

    Each added field defaults to False.

    Dependencies:
        - Depends on migration '0009_auto_20160920_1348' in the 'companies' app.
    """
    dependencies = [
        ('companies', '0009_auto_20160920_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruiter',
            options={'verbose_name': 'Recruiter', 'verbose_name_plural': 'Recruiters'},
        ),
        migrations.AddField(
            model_name='recruiter',
            name='application_process_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='job_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='site_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='team_management',
            field=models.BooleanField(default=False),
        ),
    ]
