# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 14:01


from __future__ import absolute_import
from django.db import migrations, models

"""
Migration to update the Recruiter model by adding Boolean fields for management roles.

This migration:
- Resets verbose names for the Recruiter model.
- Adds four Boolean fields representing different management permissions:
  team_management, site_management, job_management, and application_process_management.

Dependencies:
    - Depends on migration '0009_auto_20160920_1348' in the 'companies' app.
"""

class Migration(migrations.Migration):
    """Migration class to alter Recruiter model options and add management role fields."""
    dependencies = [
        ('companies', '0009_auto_20160920_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruiter',
            options={'verbose_name': 'Recruiter', 'verbose_name_plural': 'Recruiters'},
        ),
        migrations.AddField(
            model_name='recruiter',
            name='application_process_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='job_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='site_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='team_management',
            field=models.BooleanField(default=False),
        ),
    ]
