# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 17:40


from __future__ import absolute_import
from django.db import migrations, models

"""
Migration to extend the RecruiterInvitation model with management permission fields.

This migration:
- Adds four Boolean fields to the RecruiterInvitation model:
  - team_management
  - site_management
  - job_management
  - application_process_management

These fields will be used to pre-assign management roles during recruiter invitation.
"""

class Migration(migrations.Migration):
    """Migration class to add management-related Boolean fields to the RecruiterInvitation model."""
    dependencies = [
        ('companies', '0010_auto_20160920_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterinvitation',
            name='application_process_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruiterinvitation',
            name='job_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruiterinvitation',
            name='site_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruiterinvitation',
            name='team_management',
            field=models.BooleanField(default=False),
        ),
    ]
