# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-28 11:04


from __future__ import absolute_import
from django.db import migrations, models

"""
Migration to refactor recruiter permission structure.

This migration:
- Removes individual Boolean fields from the Recruiter model:
  - application_process_management
  - job_management
  - site_management
  - team_management
- Introduces a new 'membership' field (PositiveSmallIntegerField) to centralize recruiter roles.
  The 'membership' field likely encodes permission levels or recruiter roles numerically.
"""

class Migration(migrations.Migration):
    """Handles migration of the Recruiter model by consolidating multiple permission flags 
    into a single membership field."""
    dependencies = [
        ('companies', '0011_auto_20160920_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='application_process_management',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='job_management',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='site_management',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='team_management',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='membership',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
