# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-28 11:04


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to remove management permission fields from the Recruiter model 
    and add a new 'membership' field.

    This migration performs the following operations on the Recruiter model:
        - Removes the Boolean fields:
            * application_process_management
            * job_management
            * site_management
            * team_management
        - Adds a new field 'membership' of type PositiveSmallIntegerField with a default value of 1.

    The 'membership' field likely represents different membership levels or tiers.

    Dependencies:
        - Depends on migration '0011_auto_20160920_1740' in the 'companies' app.
    """
    dependencies = [
        ('companies', '0011_auto_20160920_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='application_process_management',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='job_management',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='site_management',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='team_management',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='membership',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
