# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-28 11:58


from __future__ import absolute_import
from django.db import migrations, models

"""
Migration to refactor recruiter invitation permissions.

This migration:
- Removes individual Boolean permission fields from the RecruiterInvitation model:
  - application_process_management
  - job_management
  - site_management
  - team_management
- Adds a single 'membership' field (PositiveSmallIntegerField) to encapsulate permission roles.

This change aligns the permission model of RecruiterInvitation with the updated Recruiter model structure.
"""

class Migration(migrations.Migration):
    """Replaces multiple permission-related Boolean fields in RecruiterInvitation 
    with a single numeric 'membership' field for simplified role management."""
    dependencies = [
        ('companies', '0012_auto_20160928_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterinvitation',
            name='application_process_management',
        ),
        migrations.RemoveField(
            model_name='recruiterinvitation',
            name='job_management',
        ),
        migrations.RemoveField(
            model_name='recruiterinvitation',
            name='site_management',
        ),
        migrations.RemoveField(
            model_name='recruiterinvitation',
            name='team_management',
        ),
        migrations.AddField(
            model_name='recruiterinvitation',
            name='membership',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
