# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-07 17:17


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Migration to create a new 'Ban' model and add a 'ban_list' field to the 'Company' model.

    Operations performed:
    - Created 'Ban' model with fields:
        * id: Auto-incrementing primary key.
        * email: EmailField to store banned email addresses (optional).
        * duration: PositiveIntegerField indicating the duration of the ban (optional).
        * add_date: DateTimeField recording when the ban was added (auto set on creation).
        * ban_function: TextField for additional ban-related information or function description.
        * company: ForeignKey to 'Company', linking each ban to a specific company (optional).
    - Added 'ban_list' field to the 'Company' model as a TextField (default None), 
      presumably to store a serialized list or details of bans related to the company.

    Model options:
    - 'Ban' model is configured with verbose names 'Ban' and 'Bans'.

    Dependencies:
    - Depends on migration '0013_auto_20160928_1158' in the 'companies' app.
    """
    dependencies = [
        ('companies', '0013_auto_20160928_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name=b'Email')),
                ('duration', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('ban_function', models.TextField(default=None)),
            ],
            options={
                'verbose_name': 'Ban',
                'verbose_name_plural': 'Bans',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='ban_list',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='ban',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
    ]
