# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-07 17:17


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion

"""
Migration to introduce a 'Ban' model for managing banned users within a company context.

This migration:
- Creates a new 'Ban' model to store information about banned users, including email, ban duration,
  associated company, and a custom function to define ban behavior.
- Adds a 'ban_list' text field to the 'Company' model to store serialized or reference information
  related to bans.
"""

class Migration(migrations.Migration):
    """Defines the schema changes for introducing the Ban model and updating the Company model."""
    dependencies = [
        ('companies', '0013_auto_20160928_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name=b'Email')),
                ('duration', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('ban_function', models.TextField(default=None)),
            ],
            options={
                'verbose_name': 'Ban',
                'verbose_name_plural': 'Bans',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='ban_list',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='ban',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
    ]
