# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-08 22:22


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_auto_20161007_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ban_list',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
