# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-05 10:39


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Migration to update the 'Wallet' model by removing some fields and adding new ones.

    Operations performed:
    - Removed the 'adds' field from the 'Wallet' model.
    - Removed the 'redeems' field from the 'Wallet' model.
    - Added a 'currency' ForeignKey field referencing the 'Currency' model from the 'common' app. 
      This field is optional (can be null or blank) and uses CASCADE deletion.
    - Added a 'last_updated' DateTimeField to track the last modification time of the wallet. 
      This field auto-updates on each save and allows null values.

    Dependencies:
    - Depends on migration '0004_auto_20160908_2311' from 'common' app.
    - Depends on migration '0015_auto_20161008_2222' from 'companies' app.
    """
    dependencies = [
        ('common', '0004_auto_20160908_2311'),
        ('companies', '0015_auto_20161008_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='adds',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='redeems',
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Currency'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
