# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-05 10:39


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion

"""
Migration to modify the Wallet model in the companies app.

This migration removes the 'adds' and 'redeems' fields from the Wallet model.
It also introduces a new ForeignKey field 'currency' to reference the Currency model
from the common app, and a 'last_updated' DateTimeField to track updates to the wallet.
"""

class Migration(migrations.Migration):
    """
    Applies changes to the Wallet model:
    - Removes obsolete fields 'adds' and 'redeems'.
    - Adds a ForeignKey 'currency' to reference the Currency model, allowing wallets
      to be associated with a specific currency type.
    - Adds a 'last_updated' DateTimeField that automatically records the timestamp of 
      the most recent modification to the wallet entry.
    """
    dependencies = [
        ('common', '0004_auto_20160908_2311'),
        ('companies', '0015_auto_20161008_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='adds',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='redeems',
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Currency'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
