# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 17:57


from __future__ import absolute_import
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    """
    Migration to alter the 'description' field of the 'Company' model.

    Changes made:
    - Updated the 'description' field to use CKEditor's RichTextField.
    - The field allows blank and null values and has a default of None.
    - The verbose name for this field is set to 'Short Description'.

    Dependency:
    - Depends on the previous migration '0016_auto_20161105_1039' in the 'companies' app.
    """
    dependencies = [
        ('companies', '0016_auto_20161105_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='Short Description'),
        ),
    ]
