# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 17:57


from __future__ import absolute_import
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_auto_20161105_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='Short Description'),
        ),
    ]
