# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 17:57


from __future__ import absolute_import
import ckeditor.fields
from django.db import migrations

"""
Migration to alter the 'description' field of the Company model.

This change replaces the plain text field with a RichTextField from the ckeditor package,
enabling rich-text formatting in the company's short description.
"""

class Migration(migrations.Migration):
    """
    Alters the 'description' field in the Company model to use CKEditor's RichTextField.

    This allows company descriptions to include HTML content such as headings, lists,
    links, and formatted text, improving presentation flexibility in the admin interface
    and other rich content displays.
    """
    dependencies = [
        ('companies', '0016_auto_20161105_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='Short Description'),
        ),
    ]
