# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-21 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_company_site_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='above_jobs',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='below_jobs',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
