# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-21 12:44


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to add 'above_jobs' and 'below_jobs' fields to the 'Company' model.

    Changes made:
    - Added 'above_jobs' field as a TextField with no default (empty string set as default).
    - Added 'below_jobs' field as a TextField with no default (empty string set as default).
    - Both fields are intended to store text content related to job postings or job display customization.

    Dependency:
    - Depends on the previous migration '0018_company_site_template' in the 'companies' app.
    """
    dependencies = [
        ('companies', '0018_company_site_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='above_jobs',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='below_jobs',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
