# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-02 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_auto_20170621_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='above_jobs',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='below_jobs',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
    ]
