# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-11 19:12


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Migration to create the 'ExternalReferal' model.

    Model fields:
    - id: Auto-incrementing primary key.
    - name: CharField with max length 50, default empty string.
    - active: BooleanField indicating if the referral is active, defaults to True.
    - company: ForeignKey to the 'Company' model with cascade delete behavior.

    Model options:
    - verbose_name set to 'External Referal'.
    - verbose_name_plural set to 'External Referals'.

    Dependencies:
    - Depends on migration '0020_auto_20170802_1348' from the 'companies' app.
    """
    dependencies = [
        ('companies', '0020_auto_20170802_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalReferal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
            options={
                'verbose_name': 'External Referal',
                'verbose_name_plural': 'External Referals',
            },
        ),
    ]
