# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-11 19:12


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion

"""
Migration to create the ExternalReferal model.

This model tracks external referrals linked to a company. It includes:
- id: Auto-generated primary key.
- name: A short name or label for the referral (max 50 chars, defaults to empty string).
- active: A boolean indicating if the referral is active (default True).
- company: ForeignKey linking the referral to a specific Company, with cascading deletes.

Model metadata:
- verbose_name: 'External Referal'
- verbose_name_plural: 'External Referals'
"""

class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_auto_20170802_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalReferal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
            options={
                'verbose_name': 'External Referal',
                'verbose_name_plural': 'External Referals',
            },
        ),
    ]
