# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-11 19:31


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion

"""
Migration to alter the 'company' field in the ExternalReferal model.

Changes made:
- The 'company' ForeignKey field is now allowed to be blank and null.
- Default value for 'company' set to None.
- On delete behavior remains CASCADE.

This allows ExternalReferal instances to optionally not be linked to any Company.
"""

class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_externalreferal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalreferal',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
    ]
