# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-11 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_auto_20171011_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalreferal',
            name='referal_type',
            field=models.CharField(choices=[('JB', 'Job Board'), ('ER', 'External Referer')], default='JB', max_length=2),
            preserve_default=False,
        ),
    ]
