# Generated by Django 5.2.1 on 2025-06-12 14:12

import django.core.validators
import django.db.models.deletion
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_country_continent_alter_country_iso2_code_and_more'),
        ('companies', '0023_externalreferal_referal_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='above_jobs',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='below_jobs',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company_industry', verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='logos_TRM/logo_TRM_company_default.png', max_length=200, null=True, upload_to='companies/logos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='twitter',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'))], verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='externalreferal',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='externalreferal',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='externalreferal',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.recommendation_status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='recruiterinvitation',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='recruiterinvitation',
            name='invited_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Invited by'),
        ),
        migrations.AlterField(
            model_name='recruiterinvitation',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='company',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency'),
        ),
    ]
