# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-13 23:19


from __future__ import absolute_import
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='socialmultishareoauth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.TextField()),
                ('oauth_secret', models.TextField()),
                ('identifier', models.TextField()),
                ('media', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('LI', 'Linked In')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'socialmultishareoauth',
                'verbose_name_plural': 'socialmultishareoauths',
            },
        ),
    ]
