from django.urls import path
from .views import (
    VacancyActiveStatusAPIView,
    FirstSearchAPIView,
    CommentsAPIView,
    VacancyAndFilterAPIView,
    FilterVacanciesByStateAPIView,
    EmploymentTypeFilterAPIView,
    FilterVacanciesByPubDateAPIView,
    VacancySearchAPIView,
    VacancyDetailsAPIView,
    VacancyStageDetailsAPIView,
    VacancyToPDFAPIView,
    VacanciesByCompanyAPIView,
    CreateVacanciesAPIView,
    PublicApplyAPIView,
    NewApplicationAPIView,
    ResolveApplicationConflictsAPIView,
    CompleteApplicationAPIView,
    VacancyTalentSourcingAPIView,
)

urlpatterns = [
    path('status/', VacancyActiveStatusAPIView.as_view(), name='vacancy_active_status'),
    path('search/first/', FirstSearchAPIView.as_view(), name='first_search'),
    path('comments/', CommentsAPIView.as_view(), name='vacancy_comments'),
    path('filters/', VacancyAndFilterAPIView.as_view(), name='vacancy_and_filters'),
    path('filter/state/<int:state_id>/', FilterVacanciesByStateAPIView.as_view(), name='filter_vacancies_by_state'),
    path('filter/employment-type/<int:employmentType_id>/', EmploymentTypeFilterAPIView.as_view(), name='employment_type_filter'),
    path('filter/pub-date/<int:days>/', FilterVacanciesByPubDateAPIView.as_view(), name='filter_by_pub_date'),
    path('search/', VacancySearchAPIView.as_view(), name='vacancy_search'),
    path('<int:vacancy_id>/', VacancyDetailsAPIView.as_view(), name='vacancy_details'),
    path('<int:vacancy_id>/stage/<str:vacancy_stage>/<str:stage_section>/', VacancyStageDetailsAPIView.as_view(), name='vacancy_stage_details'),
    path('<int:vacancy_id>/pdf/', VacancyToPDFAPIView.as_view(), name='vacancy_to_pdf'),
    path('company/<int:company_id>/', VacanciesByCompanyAPIView.as_view(), name='vacancies_by_company'),
    path('create/bulk/', CreateVacanciesAPIView.as_view(), name='create_vacancies_bulk'),
    path('<int:vacancy_id>/apply/public/', PublicApplyAPIView.as_view(), name='public_apply'),
    path('<int:vacancy_id>/apply/new/', NewApplicationAPIView.as_view(), name='new_application'),
    path('<int:vacancy_id>/apply/resolve/<int:card_type>/', ResolveApplicationConflictsAPIView.as_view(), name='resolve_conflicts'),
    path('<int:vacancy_id>/apply/complete/', CompleteApplicationAPIView.as_view(), name='complete_application'),
    path('<int:vacancy_id>/talent-sourcing/', VacancyTalentSourcingAPIView.as_view(), name='vacancy_talent_sourcing'),
]
