# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-15 02:22


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('vacancies', '0002_auto_20160814_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='nationality',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.Country', verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='State'),
        ),
    ]
