# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 12:00


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_vacancystage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy_status',
            options={'ordering': ['id'], 'verbose_name': 'Vacancy Status', 'verbose_name_plural': 'Vacancy Statuses'},
        ),
        migrations.AddField(
            model_name='vacancy_status',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Is Public?'),
        ),
    ]
