# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 17:00


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_auto_20160816_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='function',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Function'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='notice_period',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Notice Period'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Skills'),
        ),
    ]
