# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 19:06


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_auto_20160816_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancystage',
            name='candidates',
        ),
        migrations.AddField(
            model_name='postulate',
            name='tag',
            field=models.CharField(default=None, max_length=200, verbose_name='Application Tag'),
        ),
        migrations.AddField(
            model_name='postulate',
            name='vacancy_stage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vacancies.VacancyStage'),
            preserve_default=False,
        ),
    ]
