# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 20:45


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_auto_20160819_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='employmentExperience',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='maxEmploymentExperience',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='max_experience', to='vacancies.Employment_Experience', verbose_name='Maximum Experience'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='minEmploymentExperience',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='min_experience', to='vacancies.Employment_Experience', verbose_name='Minimum Experience'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(blank=True, default=None, max_length=70, null=True, verbose_name='Job Role'),
        ),
    ]
