# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 16:31


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_auto_20160821_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_postulate',
            name='vacancy_stage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vacancies.VacancyStage'),
            preserve_default=False,
        ),
    ]
