# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 17:37


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_public_postulate_vacancy_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulate',
            name='fnalize',
            field=models.BooleanField(default=False, verbose_name=b'Selected'),
        ),
        migrations.AlterField(
            model_name='postulate',
            name='vacancy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postulated', to='vacancies.Vacancy', verbose_name='Vacancy'),
        ),
        migrations.AlterField(
            model_name='public_postulate',
            name='vacancy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_postulated', to='vacancies.Vacancy', verbose_name='Vacancy'),
        ),
    ]
