# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 17:46


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_auto_20160825_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulate',
            old_name='fnalize',
            new_name='finalize',
        ),
        migrations.AddField(
            model_name='public_postulate',
            name='finalize',
            field=models.BooleanField(default=False, verbose_name=b'Selected'),
        ),
    ]
