# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 10:47


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_auto_20160825_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='industry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Company_Industry', verbose_name='Industry'),
        ),
    ]
