# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 18:17


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0014_public_postulate_discard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulate',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Application Tag'),
        ),
    ]
