# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-03 16:00


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0015_auto_20160902_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_reason',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Vacancy Reason for Closing'),
        ),
    ]
