# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 23:30


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20160908_2311'),
        ('companies', '0005_auto_20160908_2305'),
        ('vacancies', '0017_auto_20160906_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_postulate',
            name='isRecruiter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='public_postulate',
            name='recruiter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Recruiter', verbose_name='Recruiter'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='currency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Currency', verbose_name='Currency'),
        ),
    ]
