# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 20:12


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0018_auto_20160908_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employment_experience',
            options={'ordering': ['id'], 'verbose_name': 'Employment Experience', 'verbose_name_plural': 'Employment Experiences'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='max_age',
            field=models.CharField(blank=True, choices=[(1, 'Any'), [b'18', b'18'], [b'19', b'19'], [b'20', b'20'], [b'21', b'21'], [b'22', b'22'], [b'23', b'23'], [b'24', b'24'], [b'25', b'25'], [b'26', b'26'], [b'27', b'27'], [b'28', b'28'], [b'29', b'29'], [b'30', b'30'], [b'31', b'31'], [b'32', b'32'], [b'33', b'33'], [b'34', b'34'], [b'35', b'35'], [b'36', b'36'], [b'37', b'37'], [b'38', b'38'], [b'39', b'39'], [b'40', b'40'], [b'41', b'41'], [b'42', b'42'], [b'43', b'43'], [b'44', b'44'], [b'45', b'45'], [b'46', b'46'], [b'47', b'47'], [b'48', b'48'], [b'49', b'49'], [b'50', b'50'], [b'51', b'51'], [b'52', b'52'], [b'53', b'53'], [b'54', b'54'], [b'55', b'55'], [b'56', b'56'], [b'57', b'57'], [b'58', b'58'], [b'59', b'59'], [b'60', b'60'], [b'61', b'61'], [b'62', b'62'], [b'63', b'63'], [b'64', b'64'], [b'65', b'65']], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='min_age',
            field=models.CharField(blank=True, choices=[(1, 'Any'), [b'18', b'18'], [b'19', b'19'], [b'20', b'20'], [b'21', b'21'], [b'22', b'22'], [b'23', b'23'], [b'24', b'24'], [b'25', b'25'], [b'26', b'26'], [b'27', b'27'], [b'28', b'28'], [b'29', b'29'], [b'30', b'30'], [b'31', b'31'], [b'32', b'32'], [b'33', b'33'], [b'34', b'34'], [b'35', b'35'], [b'36', b'36'], [b'37', b'37'], [b'38', b'38'], [b'39', b'39'], [b'40', b'40'], [b'41', b'41'], [b'42', b'42'], [b'43', b'43'], [b'44', b'44'], [b'45', b'45'], [b'46', b'46'], [b'47', b'47'], [b'48', b'48'], [b'49', b'49'], [b'50', b'50'], [b'51', b'51'], [b'52', b'52'], [b'53', b'53'], [b'54', b'54'], [b'55', b'55'], [b'56', b'56'], [b'57', b'57'], [b'58', b'58'], [b'59', b'59'], [b'60', b'60'], [b'61', b'61'], [b'62', b'62'], [b'63', b'63'], [b'64', b'64'], [b'65', b'65']], default=None, max_length=2, null=True),
        ),
    ]
