# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-13 17:02


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0019_auto_20160912_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='max_salary',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Maximum Salary'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='min_salary',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Minimum Salary'),
        ),
    ]
