# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-29 18:37


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20160928_1158'),
        ('vacancies', '0023_vacancystage_criteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('comment_type', models.PositiveSmallIntegerField()),
                ('logtime', models.DateTimeField(auto_now_add=True, verbose_name=b'TimeStamp')),
                ('postulate', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.Postulate')),
                ('public_postulate', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.Public_Postulate')),
                ('recruiter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Recruiter')),
                ('stage', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.VacancyStage')),
            ],
            options={
                'ordering': ('-logtime', 'stage'),
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AlterField(
            model_name='postulate_stage',
            name='postulate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.Public_Postulate', verbose_name=b'Postulate Stage'),
        ),
    ]
