# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-30 18:20


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0025_auto_20160930_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancystage',
            name='criteria',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
