# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 15:23


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0026_vacancystage_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulate_stage',
            name='postulate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.Postulate', verbose_name=b'Postulate Stage'),
        ),
        migrations.AlterField(
            model_name='public_postulate_stage',
            name='postulate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.Public_Postulate', verbose_name=b'Postulate Stage'),
        ),
    ]
