# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 16:15


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20160928_1158'),
        ('vacancies', '0027_auto_20161001_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulate_score',
            name='recruiter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Recruiter'),
        ),
    ]
