# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-06 16:02


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0028_postulate_score_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulate',
            name='withdraw',
            field=models.BooleanField(default=False, verbose_name='Wihdrawen'),
        ),
    ]
