# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-29 20:56


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0031_auto_20161008_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
