# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-29 21:39


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0032_auto_20161029_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='stage_section',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
