# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-24 11:17


from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0033_comment_stage_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ('-pub_date', '-id'), 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
    ]
