# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-27 17:59


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0034_auto_20161224_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_postulate',
            name='filecontent',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
    ]
