# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-04 13:12


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0035_public_postulate_filecontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate_fav',
            options={'ordering': ('-vacancy', '-add_date'), 'verbose_name': 'Favourite Job', 'verbose_name_plural': 'Favourite Jobs'},
        ),
        migrations.AlterModelOptions(
            name='vacancy_files',
            options={'ordering': ('-vacancy', '-add_date', 'random_number'), 'verbose_name': 'File for Job', 'verbose_name_plural': 'Files for Job'},
        ),
        migrations.AlterModelOptions(
            name='vacancy_status',
            options={'ordering': ['id'], 'verbose_name': 'Job Status', 'verbose_name_plural': 'Job Statuses'},
        ),
        migrations.AlterModelOptions(
            name='vacancystage',
            options={'ordering': ['order'], 'verbose_name': 'Job Stage', 'verbose_name_plural': 'Job Stages'},
        ),
        migrations.AlterField(
            model_name='candidate_fav',
            name='vacancy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vacancies.Vacancy', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='postulate',
            name='vacancy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postulated', to='vacancies.Vacancy', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='postulate_stage',
            name='vacancy_stage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.VacancyStage', verbose_name=b'Job Stage'),
        ),
        migrations.AlterField(
            model_name='public_postulate',
            name='vacancy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_postulated', to='vacancies.Vacancy', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='public_postulate_stage',
            name='vacancy_stage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.VacancyStage', verbose_name=b'Job Stage'),
        ),
        migrations.AlterField(
            model_name='question',
            name='vacancy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.Vacancy', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='stagecriterion',
            name='vacancy_stage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.VacancyStage', verbose_name=b'Job Stage'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancies_number',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Number of Jobs'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_reason',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Job Reason for Closing'),
        ),
        migrations.AlterField(
            model_name='vacancy_files',
            name='vacancy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.Vacancy', verbose_name=b'Job'),
        ),
        migrations.AlterField(
            model_name='vacancystage',
            name='vacancy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.Vacancy', verbose_name='Job'),
        ),
    ]
