# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-17 13:03


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0036_auto_20170104_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancystage',
            options={'ordering': ['order'], 'verbose_name': 'Job Process', 'verbose_name_plural': 'Job Processes'},
        ),
        migrations.AddField(
            model_name='postulate',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=50, null=True, verbose_name='Description'),
        ),
    ]
