# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-19 15:17


from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_remove_activity_public_postulate'),
        ('vacancies', '0038_public_postulate_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public_postulate',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='public_postulate',
            name='recruiter',
        ),
        migrations.RemoveField(
            model_name='public_postulate',
            name='vacancy',
        ),
        migrations.RemoveField(
            model_name='public_postulate',
            name='vacancy_stage',
        ),
        migrations.RemoveField(
            model_name='public_postulate_stage',
            name='postulate',
        ),
        migrations.RemoveField(
            model_name='public_postulate_stage',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='public_postulate_stage',
            name='vacancy_stage',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='public_postulate',
        ),
        migrations.DeleteModel(
            name='Public_Postulate',
        ),
        migrations.DeleteModel(
            name='Public_Postulate_Stage',
        ),
    ]
