# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-24 12:39


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0039_auto_20170119_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulate',
            name='is_recruiter',
            field=models.BooleanField(default=False, verbose_name=b'Added by Recruiter?'),
        ),
    ]
