# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-10 16:36


from __future__ import absolute_import
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0040_postulate_is_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='unpub_date',
            field=models.DateField(default=datetime.date(2017, 4, 8), verbose_name='Date of unpublication'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.DateField(default=datetime.date(2017, 3, 10), verbose_name='Date of publication'),
        ),
    ]
