# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-13 14:29


from __future__ import absolute_import
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0041_auto_20170310_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publish_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, choices=[('1', 'Published'), ('2', 'Un-Published')], default=None, max_length=2, null=True)),
                ('action_date', models.DateField(auto_now_add=True, verbose_name='On')),
            ],
            options={
                'verbose_name': 'Publish_History',
                'verbose_name_plural': 'Publish_Histories',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='Is Expired?'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='scheduled',
            field=models.BooleanField(default=False, verbose_name='Is Scheduled?'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of publication'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='unpub_date',
            field=models.DateField(default=datetime.date(2017, 4, 11), verbose_name='Date of unpublication'),
        ),
        migrations.AddField(
            model_name='publish_history',
            name='vacancy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.Vacancy', verbose_name='Job'),
        ),
    ]
