# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-13 23:29


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0043_remove_vacancy_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='editing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Editing Date'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
    ]
