# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-14 00:27


from __future__ import absolute_import
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0044_auto_20170313_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='unpub_date',
            field=models.DateField(default=datetime.date(2017, 4, 12), verbose_name='Date of unpublication'),
        ),
    ]
