# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-14 13:01


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0046_auto_20170314_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulate',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Description'),
        ),
    ]
