# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-20 17:56


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0047_auto_20170314_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Tag Name')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Add Date')),
            ],
            options={
                'verbose_name': 'Job Tags',
            },
        ),
        migrations.AddField(
            model_name='postulate',
            name='tags',
            field=models.ManyToManyField(default=None, to='vacancies.VacancyTags'),
        ),
    ]
