# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-20 19:43


from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0048_auto_20170320_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancytags',
            name='vacancy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.Vacancy'),
        ),
    ]
