# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-02 10:41


from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0050_auto_20170402_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulate',
            name='has_filled_custom_form',
            field=models.BooleanField(default=False, verbose_name=b'Filled Custom Form?'),
        ),
    ]
