# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-02 15:53


from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0051_postulate_has_filled_custom_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='template',
            new_name='form_template',
        ),
    ]
