# Generated by Django 5.2.1 on 2025-06-12 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_alter_academic_candidate_alter_candidate_first_name_and_more'),
        ('common', '0009_alter_country_continent_alter_country_iso2_code_and_more'),
        ('companies', '0024_alter_ban_company_alter_ban_email_and_more'),
        ('customField', '0004_alter_field_is_required_and_more'),
        ('vacancies', '0054_auto_20171107_1908'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_fav',
            name='candidate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidate', verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='candidate_fav',
            name='vacancy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vacancies.vacancy', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='logtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='TimeStamp'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='postulate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.postulate'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='recruiter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.recruiter'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.vacancystage'),
        ),
        migrations.AlterField(
            model_name='postulate',
            name='candidate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidate', verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='postulate',
            name='finalize',
            field=models.BooleanField(default=False, verbose_name='Selected'),
        ),
        migrations.AlterField(
            model_name='postulate',
            name='has_filled_custom_form',
            field=models.BooleanField(blank=True, default=False, verbose_name='Filled Custom Form?'),
        ),
        migrations.AlterField(
            model_name='postulate',
            name='is_recruiter',
            field=models.BooleanField(blank=True, default=False, verbose_name='Added by Recruiter?'),
        ),
        migrations.AlterField(
            model_name='postulate',
            name='recruiter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.recruiter'),
        ),
        migrations.AlterField(
            model_name='postulate',
            name='vacancy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulated', to='vacancies.vacancy', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='postulate',
            name='vacancy_stage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.vacancystage'),
        ),
        migrations.AlterField(
            model_name='postulate_score',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Criteria Name'),
        ),
        migrations.AlterField(
            model_name='postulate_score',
            name='recruiter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.recruiter'),
        ),
        migrations.AlterField(
            model_name='postulate_stage',
            name='postulate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.postulate', verbose_name='Postulate Stage'),
        ),
        migrations.AlterField(
            model_name='postulate_stage',
            name='vacancy_stage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.vacancystage', verbose_name='Job Stage'),
        ),
        migrations.AlterField(
            model_name='publish_history',
            name='vacancy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.vacancy', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='question',
            name='vacancy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.vacancy', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='stagecriterion',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Criteria Name'),
        ),
        migrations.AlterField(
            model_name='stagecriterion',
            name='vacancy_stage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.vacancystage', verbose_name='Job Stage'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='ban',
            field=models.BooleanField(default=False, verbose_name='Ban'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='ban_all',
            field=models.BooleanField(default=False, verbose_name=' Ban All'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='ban_period',
            field=models.CharField(blank=True, choices=[('1', '1 month'), ('2', '2 months'), ('3', '3 months'), ('4', '4 months'), ('5', '5 months'), ('6', '6 months'), ('7', '7 months'), ('8', '8 months'), ('9', '9 months'), ('10', '10 months'), ('11', '11 months')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='form_template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customField.template'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='has_custom_form',
            field=models.BooleanField(blank=True, default=False, verbose_name='Has Custom Form?'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='max_age',
            field=models.CharField(blank=True, choices=[(1, 'Any'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'), ('57', '57'), ('58', '58'), ('59', '59'), ('60', '60'), ('61', '61'), ('62', '62'), ('63', '63'), ('64', '64'), ('65', '65')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='min_age',
            field=models.CharField(blank=True, choices=[(1, 'Any'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'), ('57', '57'), ('58', '58'), ('59', '59'), ('60', '60'), ('61', '61'), ('62', '62'), ('63', '63'), ('64', '64'), ('65', '65')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='recruiters',
            field=models.ManyToManyField(default=None, to='companies.recruiter', verbose_name='Recruiter'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='vacancy_files',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='vacancy_files',
            name='random_number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='vacancy_files',
            name='vacancy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.vacancy', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='vacancytags',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Tag Name'),
        ),
        migrations.AlterField(
            model_name='vacancytags',
            name='vacancy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.vacancy'),
        ),
    ]
