# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-22 06:17


from __future__ import absolute_import
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

"""
Initial migration for the 'Schedule' model in the 'scheduler' app.

This migration creates the 'Schedule' model with the following fields:
- id: Primary key (AutoField).
- scheduled_on: DateTimeField indicating when the schedule is set.
- offset: IntegerField representing time offset in minutes.
- status: CharField with choices 'Pending' or 'Completed', allowing null and blank.
- application: ForeignKey to 'vacancies.Postulate' representing the related application.
- user: ForeignKey to the user model who scheduled the event.

Model metadata includes verbose names for singular and plural forms.

Dependencies:
- Swappable dependency on the user model from settings.AUTH_USER_MODEL.
- Dependency on the '0049_vacancytags_vacancy' migration of the 'vacancies' app.
"""

class Migration(migrations.Migration):
    """
    Migration class to create the Schedule model.

    This class contains the dependencies required before applying this migration
    and the operations that define the creation of the Schedule model with its
    respective fields and options.
    """
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0049_vacancytags_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_on', models.DateTimeField(verbose_name='Scheduled On')),
                ('offset', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('0', 'Pending'), ('1', 'Completed')], default=None, max_length=2, null=True, verbose_name='Status')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.Postulate', verbose_name='Scheduled with')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Scheduled By')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
