# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-22 06:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0049_vacancytags_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_on', models.DateTimeField(verbose_name='Scheduled On')),
                ('offset', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('0', 'Pending'), ('1', 'Completed')], default=None, max_length=2, null=True, verbose_name='Status')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.Postulate', verbose_name='Scheduled with')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Scheduled By')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
