# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-22 07:02


from __future__ import absolute_import
from django.db import migrations, models

"""
Migration to update fields in the 'Schedule' model of the 'scheduler' app.

Changes:
- Alters the 'offset' field to allow null and blank values, with a default of 0.
- Alters the 'scheduled_on' field to allow null and blank values, with a verbose name.

Dependencies:
- Depends on the initial migration '0001_initial' for the 'scheduler' app.
"""

class Migration(migrations.Migration):
    """
    Migration class to modify 'offset' and 'scheduled_on' fields in 'Schedule' model.

    This migration updates the field options to support nullable and blank values,
    improving flexibility in scheduling.
    """
    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='offset',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='scheduled_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled On'),
        ),
    ]
